就業規則の成形
mk-system/MK-Rules pull request #18
Opened 2023-02-09 09:52 UTC by t-abe-pixel

2023-02-09 09:52 UTC, t-abe-pixel commented
@katsusuke レビューよろしくお願い申し上げます。

2023-02-09 10:03 UTC, katsusuke commented on 001_就業規則.md
> +  ```
コードブロックはやめてほしいです
2行連結が問題な場合改行を2つ入れてください

```
  （前文）

  この規則は、会社と従業員が相互信頼の上に立ち、従業員の福祉の向上と社業の発展を目的として制定されたものであって、会社と従業員は、それぞれの担当する経営、職務について責任をもって積極的に、かつ誠実にその業務を遂行することにより、この目的を達成しなければならない。
```

2023-02-09 10:04 UTC, katsusuke commented on 001_就業規則.md
> +- 第１条（目的）
条は見出し4にしてください
```
#### 第１条（目的）
```

2023-02-09 10:05 UTC, katsusuke commented on 001_就業規則.md
> +  ```
- コードブロックではなくリストでお願いをします
- 先頭の全角スペースは消してください


1. この就業規則（以下「規則」という）は、株式会社エムケイシステム（以下「会社」という）の従業員の労働条件と基本的な服務規律、その他就業に関する事項について定めたものである。
2. この規則及びこの規則の付属規程に定めのないことがらについては、労働基準法その他の法令の定めによる。

2023-02-09 10:06 UTC, katsusuke requested changes
すみませんコードブロックではなくリストで対応をしてほしいです

2025-12-15 11:17 UTC, katsusuke commented
一旦クローズさせていただきます

2025-12-15 11:17 UTC, closed without merging